version: '3'
services:

  db-rezervacija:
    image: postgres
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - 5431:5431
  
  db-admin:
    image: postgres
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=AdminMicroserviceDB
    ports:
      - 5432:5432
  
  db-ocenjivanje:
    image: postgres
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=OcenjivanjeIKomentari
    ports:
      - 5433:5433
      
  db-razmena-poruka:
    image: postgres
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=RazmenaPoruka
    ports:
      - 5434:5434
  
  eureka-service:
    build: ./EurekaService
    ports:
      - 8761:8761
      
  administrator-service:
    build: ./Administrator
    environment:
      - REGISTRY_HOST=eureka-service
      - DB_HOST=db-admin
    ports:
      - 8087:8087
    depends_on:
      - eureka-service
      - db-admin    
  
  ocenjivanje-i-komentari-service:
    build: ./OcenjivanjeIKomentari
    environment:
      - REGISTRY_HOST=eureka-service
    ports:
      - 8085:8085
    depends_on:
      - eureka-service 
      - db-ocenjivanje
          
  razmena-poruka-service:
    build: ./RazmenaPoruka
    environment:
      - REGISTRY_HOST=eureka-service
    ports:
      - 8089:8089
    depends_on:
      - eureka-service 
      - db-razmena-poruka
  
  rezervacija-automobila-service:
    build: ./RezervacijaAutomobila
    environment:
      - REGISTRY_HOST=eureka-service
      - DB_HOST=db-rezervacija
    ports:
      - 8083:8083
    depends_on:
      - eureka-service
      - db-rezervacija
      
  izmena-oglasa-service:
    build: ./IzmenaOglasa
    environment:
      - REGISTRY_HOST=eureka-service
    ports:
      - 8084:8084
    depends_on:
      - eureka-service

  logovanje-i-registracija-service:
    build: ./LogovanjeIRegistracija
    environment:
      - REGISTRY_HOST=eureka-service
    ports:
      - 8086:8086
    depends_on:
      - eureka-service 

  pretraga-i-filtriranje-oglasa-service:
    build: ./PretragaIFitriranjeOglasa
    environment:
      - REGISTRY_HOST=eureka-service
    ports:
      - 8088:8088
    depends_on:
      - eureka-service 
         
  zuul-proxy:
    build: ./ZuulProxy
    environment:
      - REGISTRY_HOST=eureka-service
    ports:
      - 8080:8080
    depends_on:
      - eureka-service
      - administrator-service
      - ocenjivanje-i-komentari-service
      - razmena-poruka-service
      - rezervacija-automobila-service
      - izmena-oglasa-service
      - logovanje-i-registracija-service
      - pretraga-i-filtriranje-oglasa-service