//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.11 at 01:38:18 PM CEST 
//


package com.example.consumingwebservice;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for userTypeA.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="userTypeA"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="RENTER"/&gt;
 *     &lt;enumeration value="COMPANY"/&gt;
 *     &lt;enumeration value="ADMIN"/&gt;
 *     &lt;enumeration value="AGENT"/&gt;
 *     &lt;enumeration value="NOT_ACTIVE"/&gt;
 *     &lt;enumeration value="BLOCKED"/&gt;
 *     &lt;enumeration value="REMOVED"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "userTypeA")
@XmlEnum
public enum UserTypeA {

    RENTER,
    COMPANY,
    ADMIN,
    AGENT,
    NOT_ACTIVE,
    BLOCKED,
    REMOVED;

    public String value() {
        return name();
    }

    public static UserTypeA fromValue(String v) {
        return valueOf(v);
    }

}
